replicaCount: 1

image:
  repository: muhammedsafry/fleet-frontend
  tag: "5-b0a896d"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  NEXT_PUBLIC_VEHICLE_SERVICE_URL: "http://vehicle-service.fleet-staging.svc.cluster.local:7001"
  NEXT_PUBLIC_DRIVER_SERVICE_URL: "http://driver-service.fleet-staging.svc.cluster.local:6001"
  NEXT_PUBLIC_MAINTENANCE_SERVICE_URL: "http://maintenance-service.fleet-staging.svc.cluster.local:5001"

resources: {}
