replicaCount: 1

image:
  repository: muhammedsafry/fleet-management-front-end
  tag: "14"
  pullPolicy: Always

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30080

nameOverride: fleet-frontend
namespace: fleet-staging
