apiVersion: v1
kind: Service
metadata:
  name: fleet-frontend
spec:
  selector:
    app: fleet-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
