apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-driver
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.driver.replicaCount }}
  selector:
    matchLabels:
      app: fleet-driver
  template:
    metadata:
      labels:
        app: fleet-driver
    spec:
      containers:
        - name: fleet-driver
          image: "{{ .Values.driver.image.repository }}:{{ .Values.driver.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.driver.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.driver.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ default "staging" .Values.driver.env.SPRING_PROFILES_ACTIVE | quote }}
