apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-driver
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.driver.replicaCount }}
  selector:
    matchLabels:
      app: fleet-driver
  template:
    metadata:
      labels:
        app: fleet-driver
    spec:
      containers:
        - name: fleet-driver
          image: "{{ .Values.driver.image.repository }}:{{ .Values.driver.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.driver.service.port }}
