apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver
          image: "{{ .Values.services.driver.image }}:{{ .Values.services.driver.tag }}"
          ports:
            - containerPort: 8080
