apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-maintenance
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.maintenance.replicaCount }}
  selector:
    matchLabels:
      app: fleet-maintenance
  template:
    metadata:
      labels:
        app: fleet-maintenance
    spec:
      containers:
        - name: fleet-maintenance
          image: "{{ .Values.maintenance.image.repository }}:{{ .Values.maintenance.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.maintenance.service.port }}
          env:
            - name: FLASK_ENV
              value: "{{ .Values.maintenance.env.FLASK_ENV }}"
            - name: FLASK_APP
              value: "{{ .Values.maintenance.env.FLASK_APP }}"
            - name: PYTHONUNBUFFERED
              value: "{{ .Values.maintenance.env.PYTHONUNBUFFERED }}"
