apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance-service
  template:
    metadata:
      labels:
        app: maintenance-service
    spec:
      containers:
        - name: maintenance
          image: "{{ .Values.services.maintenance.image }}:{{ .Values.services.maintenance.tag }}"
          ports:
            - containerPort: 5001

