apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-vehicle
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.vehicle.replicaCount }}
  selector:
    matchLabels:
      app: fleet-vehicle
  template:
    metadata:
      labels:
        app: fleet-vehicle
    spec:
      containers:
        - name: fleet-vehicle
          image: "{{ .Values.vehicle.image.repository }}:{{ .Values.vehicle.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.vehicle.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.vehicle.service.targetPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ default "Staging" .Values.vehicle.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ default "http://+:8080" .Values.vehicle.env.ASPNETCORE_URLS | quote }}
            - name: CORS_ORIGINS
              value: {{ default "*" .Values.vehicle.env.CORS_ORIGINS | quote }}
            - name: ConnectionStrings__DefaultConnection
              value: {{ default "" .Values.vehicle.env.ConnectionStrings__DefaultConnection | quote }}
